
# POST https://myxbf4zyne.execute-api.ap-northeast-1.amazonaws.com/default
# Content-Type: application/json

# {
#     "text": "こんにちは"
# }


POST https://hobdfdu28a.execute-api.ap-northeast-1.amazonaws.com/default/indobizmatch
Content-Type: application/json

{
    "keyword": "VSCODE"
}
